version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://$PSQL_USER:$PSQL_PASSWORD@db:5432/$PSQL_NAME
      - REDIS_URL=redis://redis:6379/0
    command: uvicorn main:app

  worker:
    build: .
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PSQL_NAME}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}

  redis:
    image: redis:alpine

volumes:
  postgres_data:

